name: Build and Deploy Angular App to Azure Container Apps

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build Angular App
        run: npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: |
          docker build -t youracr.azurecr.io/yourimagename:${{ github.run_number }} .
          docker login youracr.azurecr.io -u username -p password
          docker push youracr.azurecr.io/yourimagename:${{ github.run_number }}

      - name: Deploy to Azure Container Apps
        run: |
          az login --service-principal -u <service_principal_id> -p <service_principal_secret> --tenant <tenant_id>
          az acr helm repo add -n youracr -g youracrResourceGroup
          az acr helm push --force --subscription <subscription_id> -n youracr youracr.azurecr.io/yourimagename:${{ github.run_number }} <chart_name>
