name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js version 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd C:\Users\sindh\SeriCulture
          npm install

      - name: Build Docker image
        run: |
          docker build -t cmtq/cloud:${{ github.run_number }} .
        
      - name: Push Docker image
        run: |
          docker login -u cmtq -p 90950047@
          docker push cmtq/cloud:${{ github.run_number }}

      - name: Run Docker Container
        run: |
          docker run -d -p 4200:4200 cmtq/cloud:${{ github.run_number }}
