name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t cmtq/cloud:${{ github.run_number }} .

      - name: Push Docker image
        run: |
          docker login -u cmtq -p 90950047@
          docker push cmtq/cloud:${{ github.run_number }}

      - name: Run Docker Container
        run: |
          docker run -d -p 4200:4200 cmtq/cloud:${{ github.run_number }}
